In [34]:
import numpy as np

# 배열 정보를 확인하기 위한 함수
def aryinfo(ary):
    print('type       : {}'.format(type(ary)))
    print('shape      : {}'.format(ary.shape))
    print('dimension  : {}'.format(ary.ndim))
    print('dtype      : {}'.format(ary.dtype))
    print('Array Data : \n', ary)

In [35]:
# 데이터 로드
data = np.loadtxt('./data/ratings.dat' , delimiter = "::", dtype=np.int64)

print("데이터 5행만 출력")
data[:5 ,:]

데이터 5행만 출력


array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [36]:
print("데이터 형태 확인")
aryinfo(data)

데이터 형태 확인
type       : <class 'numpy.ndarray'>
shape      : (1000209, 4)
dimension  : 2
dtype      : int64
Array Data : 
 [[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]


In [37]:
# 전체 평균 평점 계산

MEAN = np.mean(data[:,2])
print('전체 평균 평점:',MEAN)

전체 평균 평점: 3.581564453029317


In [38]:
# 사용자 아이디 수집
user_ids = np.unique(data[:,0])
print(user_ids)

[   1    2    3 ... 6038 6039 6040]


In [49]:
# 사용자별 평점 확인을 위한 코드 구문 작성
print("사용자 아이디별 평점 평균 확인")
print()
mean_by_user = [] # 사용자별 평점을 담을 리스트 생성
for user_id in user_ids :
    data_for_user = data[ data[:,0] == user_id, : ] # 같은 user_id를 기준으로 하는 array
    mean_for_user = data_for_user[:,2].mean() # 2열(평점)의 평균값만 추출해 저장
    mean_by_user.append([user_id, mean_for_user ])

mean_by_user[:5]

사용자 아이디별 평점 평균 확인



[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466]]

In [79]:
# 데이터관리에 유용하도록 리스트를 array로 변환시켜준다.
print("list를  numpy 배열로 변환")
mean_by_user = np.array(mean_by_user)
aryinfo(mean_by_user)

list를  numpy 배열로 변환
type       : <class 'numpy.ndarray'>
shape      : (6040, 2)
dimension  : 2
dtype      : float64
Array Data : 
 [[1.00000000e+00 4.18867925e+00]
 [2.00000000e+00 3.71317829e+00]
 [3.00000000e+00 3.90196078e+00]
 ...
 [6.03800000e+03 3.80000000e+00]
 [6.03900000e+03 3.87804878e+00]
 [6.04000000e+03 3.57771261e+00]]


In [88]:
print("각 사용자 별 평균 평점이 4점 이상인 사용자 구하기")

mean_over_four= mean_by_user[mean_by_user[:,1]>= 4]
mean_over_four[:5]

각 사용자 별 평균 평점이 4점 이상인 사용자 구하기


array([[ 1.        ,  4.18867925],
       [ 4.        ,  4.19047619],
       [ 7.        ,  4.32258065],
       [10.        ,  4.11471322],
       [17.        ,  4.07582938]])

In [90]:
# 계산 결과를 csv 파일로 저장하기
# np.savetxt("파일명",저장할 array 변수명, 파이썬포맷, 구분자)
np.savetxt("mean_over_four.csv", mean_over_four, fmt ='%.3f',delimiter =",")