#### DataFrame row index , 데이터 조작 , 인덱스 조작

- loc()  : 라벨값 기반의 2차원 인덱싱
- iloc() : 정수값 기반의 2차원 인덱싱

In [1]:
import numpy  as np
import pandas as pd
import matplotlib.pyplot as plt 
import json 

import warnings
warnings.filterwarnings(action='ignore')

from datetime import date, datetime, timedelta
from dateutil.parser import parse


print('numpy version  - ' , np.__version__)
print('pandas version - ' , pd.__version__)

numpy version  -  1.20.1
pandas version -  1.2.4


In [16]:
def seriesInfo(ary) :
    print('series - index + values \n' , ary , type(ary))
    print('index - ', type(ary.index)  , ary.index)
    print('value - ', type(ary.values) , ary.values)

def frmInfo(df) :
    display('DataFrame - ' , df)
    print('shape    - ' , df.shape )
    print('size     - ' , df.size)
    print('ndim     - ' , df.ndim)
    print('index    - ' , df.index   , type(df.index))
    print('columns  - ' , df.columns , type(df.columns))
    print('values   - \n' , df.values  , type(df.values))

In [17]:
sample_frm = pd.DataFrame(np.arange(10, 22).reshape(3,4) , 
                          index   = ['a', 'b', 'c'] , 
                          columns = ['col01', 'col02', 'col03', 'col04'])
frmInfo(sample_frm)

'DataFrame - '

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     18     19     20     21

shape    -  (3, 4)
size     -  12
ndim     -  2
index    -  Index(['a', 'b', 'c'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns  -  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values   - 
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]] <class 'numpy.ndarray'>


In [18]:
seriesInfo( sample_frm.loc['a'] )

series - index + values 
 col01    10
col02    11
col03    12
col04    13
Name: a, dtype: int32 <class 'pandas.core.series.Series'>
index -  <class 'pandas.core.indexes.base.Index'> Index(['col01', 'col02', 'col03', 'col04'], dtype='object')
value -  <class 'numpy.ndarray'> [10 11 12 13]


In [21]:
print( sample_frm.loc['a'].values , type(sample_frm.loc['a'].values) )

[10 11 12 13] <class 'numpy.ndarray'>


In [24]:
frmInfo ( sample_frm.loc[ ['a', 'c'] ] )
frmInfo ( sample_frm.iloc[ [0, 2] ] )

'DataFrame - '

col01  col02  col03  col04
a     10     11     12     13
c     18     19     20     21

shape    -  (2, 4)
size     -  8
ndim     -  2
index    -  Index(['a', 'c'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns  -  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values   - 
 [[10 11 12 13]
 [18 19 20 21]] <class 'numpy.ndarray'>


'DataFrame - '

col01  col02  col03  col04
a     10     11     12     13
c     18     19     20     21

shape    -  (2, 4)
size     -  8
ndim     -  2
index    -  Index(['a', 'c'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns  -  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values   - 
 [[10 11 12 13]
 [18 19 20 21]] <class 'numpy.ndarray'>


In [28]:
seriesInfo( sample_frm['col01'] )

series - index + values 
 a    10
b    14
c    18
Name: col01, dtype: int32 <class 'pandas.core.series.Series'>
index -  <class 'pandas.core.indexes.base.Index'> Index(['a', 'b', 'c'], dtype='object')
value -  <class 'numpy.ndarray'> [10 14 18]


In [29]:
sample_frm['col01'] > 15

a    False
b    False
c     True
Name: col01, dtype: bool

In [30]:
sample_frm.loc[ sample_frm['col01'] > 15 ]

col01  col02  col03  col04
c     18     19     20     21

In [33]:
print( type( sample_frm.loc['a' , 'col01'] ) , sample_frm.loc['a' , 'col01'])

<class 'numpy.int32'> 10


In [35]:
print( type( sample_frm.loc['a':'b' , 'col01'] ) , '\n' , sample_frm.loc['a':'b' , 'col01'])

<class 'pandas.core.series.Series'> 
 a    10
b    14
Name: col01, dtype: int32


In [36]:
print( type( sample_frm.loc['a' , : ] ) , '\n' , sample_frm.loc['a' , : ])

<class 'pandas.core.series.Series'> 
 col01    10
col02    11
col03    12
col04    13
Name: a, dtype: int32


In [37]:
print( type( sample_frm.loc['a' , ['col03' , 'col04'] ] ) , '\n' , sample_frm.loc['a' , ['col03' , 'col04'] ])

<class 'pandas.core.series.Series'> 
 col03    12
col04    13
Name: a, dtype: int32


In [38]:
frmInfo(sample_frm)

'DataFrame - '

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     18     19     20     21

shape    -  (3, 4)
size     -  12
ndim     -  2
index    -  Index(['a', 'b', 'c'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns  -  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values   - 
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]] <class 'numpy.ndarray'>


In [46]:
sample_frm.iloc[ : , 0 ]

a    10
b    14
c    18
Name: col01, dtype: int32

In [48]:
sample_frm.iloc[ 0 , -2 :  ]

col03    12
col04    13
Name: a, dtype: int32

In [49]:
sample_frm.iloc[-1]

col01    18
col02    19
col03    20
col04    21
Name: c, dtype: int32

In [51]:
sample_frm.iloc[-1] = sample_frm.iloc[-1] * 2
frmInfo(sample_frm)

'DataFrame - '

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     72     76     80     84

shape    -  (3, 4)
size     -  12
ndim     -  2
index    -  Index(['a', 'b', 'c'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns  -  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values   - 
 [[10 11 12 13]
 [14 15 16 17]
 [72 76 80 84]] <class 'numpy.ndarray'>


In [53]:
# 새로운 행 추가
sample_frm.loc['d'] = 0
frmInfo(sample_frm)

'DataFrame - '

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     72     76     80     84
d      0      0      0      0

shape    -  (4, 4)
size     -  16
ndim     -  2
index    -  Index(['a', 'b', 'c', 'd'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns  -  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values   - 
 [[10 11 12 13]
 [14 15 16 17]
 [72 76 80 84]
 [ 0  0  0  0]] <class 'numpy.ndarray'>


In [54]:
# 기존 행을 복사하여 행 추가
sample_frm.loc['e'] = sample_frm.loc['d']


In [55]:
frmInfo(sample_frm)

'DataFrame - '

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     72     76     80     84
d      0      0      0      0
e      0      0      0      0

shape    -  (5, 4)
size     -  20
ndim     -  2
index    -  Index(['a', 'b', 'c', 'd', 'e'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns  -  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values   - 
 [[10 11 12 13]
 [14 15 16 17]
 [72 76 80 84]
 [ 0  0  0  0]
 [ 0  0  0  0]] <class 'numpy.ndarray'>


In [56]:
# 새로운 열 추가
sample_frm['col05'] = sample_frm['col04'] 

In [57]:
frmInfo(sample_frm)

'DataFrame - '

col01  col02  col03  col04  col05
a     10     11     12     13     13
b     14     15     16     17     17
c     72     76     80     84     84
d      0      0      0      0      0
e      0      0      0      0      0

shape    -  (5, 5)
size     -  25
ndim     -  2
index    -  Index(['a', 'b', 'c', 'd', 'e'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns  -  Index(['col01', 'col02', 'col03', 'col04', 'col05'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values   - 
 [[10 11 12 13 13]
 [14 15 16 17 17]
 [72 76 80 84 84]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]] <class 'numpy.ndarray'>


In [61]:
sample_frm.iloc[1][1]

15

In [63]:
score_data = {
    'kor'  : [80,90,70,30],
    'eng'  : [90,70,60,40],
    'math' : [90,60,90,70] 
}
columns = ['kor','eng','math']
index   = ['김지은', '황인범', '김정수', '최호진']

score_frm = pd.DataFrame(score_data , index = index , columns = columns)
frmInfo(score_frm)

'DataFrame - '

kor  eng  math
김지은   80   90    90
황인범   90   70    60
김정수   70   60    90
최호진   30   40    70

shape    -  (4, 3)
size     -  12
ndim     -  2
index    -  Index(['김지은', '황인범', '김정수', '최호진'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns  -  Index(['kor', 'eng', 'math'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values   - 
 [[80 90 90]
 [90 70 60]
 [70 60 90]
 [30 40 70]] <class 'numpy.ndarray'>


#### 위 데이터를 활용한 [실습]
- 모든 학생의 각 과목 평균 점수를 새로운 열로 추가하라
- 최호진 학생의 영어 점수를 90점으로 수정하고 평균 점수도 다시 계산하라
- 김지은 학생의 점수를 데이터 프레임으로 만들어라
-김정수 학생의 점수를 시리즈로 출력하라
- 황인범 학생의 국어점수와 수학점수를 100점으로 수정하고 평균 점수도 다시 계산하라


In [67]:
score_frm['average'] = np.mean(score_frm , axis=1).round(2)

In [68]:
score_frm

kor  eng  math  average
김지은   80   90    90    86.67
황인범   90   70    60    73.33
김정수   70   60    90    73.33
최호진   30   40    70    46.67

In [75]:
# score_frm['eng']['최호진']
score_frm.loc['최호진' , 'eng'] = 90
score_frm['average'] = np.mean(score_frm[['kor', 'eng', 'math']] , axis=1).round(2)

In [76]:
score_frm

kor  eng  math  average
김지은   80   90    90    86.67
황인범   90   70    60    73.33
김정수   70   60    90    73.33
최호진   30   90    70    63.33

In [78]:
score_frm.loc[['김지은']]

kor  eng  math  average
김지은   80   90    90    86.67

In [79]:
score_frm.loc['김정수']

kor        70.00
eng        60.00
math       90.00
average    73.33
Name: 김정수, dtype: float64

In [81]:
score_frm.loc['황인범' , ['kor' , 'math']] = 100

In [83]:
score_frm['average'] = np.mean(score_frm[['kor', 'eng', 'math']] , axis=1).round(2)
score_frm

kor  eng  math  average
김지은   80   90    90    86.67
황인범  100   70   100    90.00
김정수   70   60    90    73.33
최호진   30   90    70    63.33

- 데이터프레임 조작 , count()

In [85]:
tmp_series = pd.Series(range(10))
tmp_series[5] = np.NaN

In [87]:
tmp_series.count()

9

In [88]:
cnt_frm = pd.DataFrame(np.random.randint(5, size=(4,4)))
cnt_frm

0  1  2  3
0  1  3  1  2
1  0  0  1  0
2  2  0  4  0
3  4  1  1  1

In [89]:
cnt_frm.count()

0    4
1    4
2    4
3    4
dtype: int64

In [90]:
cnt_frm.iloc[1,0] = np.NaN
cnt_frm.iloc[3,0] = np.NaN
cnt_frm.iloc[2,3] = np.NaN
cnt_frm

0  1  2    3
0  1.0  3  1  2.0
1  NaN  0  1  0.0
2  2.0  0  4  NaN
3  NaN  1  1  1.0

In [91]:
cnt_frm.count()

0    2
1    4
2    4
3    3
dtype: int64

#### 타이타닉 데이터를 이용한 [실습]

In [93]:
import seaborn as sns
datasets = sns.load_dataset('titanic')
print('type - ')
print( type(datasets))

type - 
<class 'pandas.core.frame.DataFrame'>


In [94]:
titanic_dataset = pd.read_csv('./data/titanic_train.csv')
print('type - ')
print( type(titanic_dataset))

type - 
<class 'pandas.core.frame.DataFrame'>


In [95]:
frmInfo(datasets)

'DataFrame - '

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

shape    -  (891, 15)
size     -  13365
ndim     -  2
index    -  RangeIndex(start=0, stop=891, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
columns  -  Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object') <class 'pandas.core.indexes.base.Index'>
values   - 
 [[0 3 'male' ... 'Southampton' 'no' False]
 [1 1 'female' ... 'Cherbourg' 'yes' False]
 [1 3 'female' ... 'Southampton' 'yes' True]
 ...
 [0 3 'female' ... 'Southampton' 'no' False]
 [1 1 'male' ... 'Cherbourg' 'yes' True]
 [0 3 'male' ... 'Queenstown' 'no' True]] <class 'numpy.ndarray'>


In [97]:
frmInfo(titanic_dataset)

'DataFrame - '

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

shape    -  (891, 12)
size     -  10692
ndim     -  2
index    -  RangeIndex(start=0, stop=891, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
columns  -  Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object') <class 'pandas.core.indexes.base.Index'>
values   - 
 [[1 0 3 ... 7.25 nan 'S']
 [2 1 1 ... 71.2833 'C85' 'C']
 [3 1 3 ... 7.925 nan 'S']
 ...
 [889 0 3 ... 23.45 nan 'S']
 [890 1 1 ... 30.0 'C148' 'C']
 [891 0 3 ... 7.75 nan 'Q']] <class 'numpy.ndarray'>


In [98]:
datasets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [101]:
datasets.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [102]:
datasets.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [103]:
datasets.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [104]:
datasets.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [107]:
datasets['class'].value_counts()

Third     491
First     216
Second    184
Name: class, dtype: int64

In [108]:
datasets['class'].value_counts().values

array([491, 216, 184], dtype=int64)

In [109]:
datasets['new_col'] = 0 

In [110]:
datasets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
 15  new_col      891 non-null    int64   
dtypes: bool(2), category(2), float64(2), int64(5), object(5)
memory usage: 87.6+ KB


In [111]:
del datasets['new_col']

In [112]:
datasets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [113]:
# age_by_10 컬럼 추가하고자 한다
# age 컬럼의 값에 10살을 더한 값으로 일괄 적용한다
datasets['age_by_10'] = datasets['age'] + 10
datasets.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  
0    man        True  NaN  Southampton    no  False       32.0  
1  woman       False    C    Cherbourg   yes  False       48.0  
2  woman       False  NaN  Southampton   yes   True       36.0  
3  woman       False    C  Southampton   yes  False       45.0  
4    man        True  NaN  Southampton    no   True       45.0

In [114]:
# parch와 sibSp의 값과 1을 더한 family_no 컬럼 생성
datasets['family_no'] = datasets['parch']+ datasets['sibsp'] + 1 
datasets.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  family_no  
0    man        True  NaN  Southampton    no  False       32.0          2  
1  woman       False    C    Cherbourg   yes  False       48.0          2  
2  woman       False  NaN  Southampton   yes   True       36.0          1  
3  woman       False    C  Southampton   yes  False       45.0          2  
4    man        True  NaN  Southampton    no   True       45.0          1

- 새로만든 두개의 피처를 삭제한다면?
- drop(label = , axis =  , inplace = )
- axis = 1 (열) , axis = 0 (행) 

In [115]:
datasets_drop_frm = datasets.drop(['age_by_10', 'family_no'] , axis = 1 , inplace = False )  

In [118]:
datasets_drop_frm.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

- 만약 3개의 행을 삭제하고 싶다면?


In [119]:
datasets_drop_frm = datasets.drop([0,1,2] , axis = 0 , inplace = False )  
datasets_drop_frm.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   
6         0       1    male  54.0      0      0  51.8625        S  First   
7         0       3    male   2.0      3      1  21.0750        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  family_no  
3  woman       False    C  Southampton   yes  False       45.0          2  
4    man        True  NaN  Southampton    no   True       45.0          1  
5    man        True  NaN   Queenstown    no   True        NaN          1  
6    man        True    E  Southampton    no   True       64.0          1  
7  child       False  NaN  Southampton    no  False       12.0          5

In [126]:
datasets.index[ : 10].values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [128]:
datasets.columns[ : 10].values

array(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who'], dtype=object)

In [140]:
fare_series = datasets['fare']
print('type - ' , type(fare_series))
print()
print('values type - ', type(fare_series.values) )
# print(fare_series.values)

print()
print('max - ' , fare_series.max())
print('min - ' , fare_series.min())
print('sum - ' , fare_series.sum())


type -  <class 'pandas.core.series.Series'>

values type -  <class 'numpy.ndarray'>

max -  512.3292
min -  0.0
sum -  28693.9493


- 인덱스를 재 정의하는 방법?
- reset_index() : 새로운 인덱스 할당, 기존 인덱스를 열로 추가하는 방법


In [143]:
reset_index_frm = datasets_drop_frm.reset_index(inplace = False)
reset_index_frm.head(10)

index  survived  pclass     sex   age  sibsp  parch     fare embarked  \
0      3         1       1  female  35.0      1      0  53.1000        S   
1      4         0       3    male  35.0      0      0   8.0500        S   
2      5         0       3    male   NaN      0      0   8.4583        Q   
3      6         0       1    male  54.0      0      0  51.8625        S   
4      7         0       3    male   2.0      3      1  21.0750        S   
5      8         1       3  female  27.0      0      2  11.1333        S   
6      9         1       2  female  14.0      1      0  30.0708        C   
7     10         1       3  female   4.0      1      1  16.7000        S   
8     11         1       1  female  58.0      0      0  26.5500        S   
9     12         0       3    male  20.0      0      0   8.0500        S   

    class    who  adult_male deck  embark_town alive  alone  age_by_10  \
0   First  woman       False    C  Southampton   yes  False       45.0   
1   Third    man        True  NaN  Southampton    no   True       45.0   
2   Third    man        True  NaN   Queenstown    no   True        NaN   
3   First    man        True    E  Southampton    no   True       64.0   
4   Third  child       False  NaN  Southampton    no  False       12.0   
5   Third  woman       False  NaN  Southampton   yes  False       37.0   
6  Second  child       False  NaN    Cherbourg   yes  False       24.0   
7   Third  child       False    G  Southampton   yes  False       14.0   
8   First  woman       False    C  Southampton   yes   True       68.0   
9   Third    man        True  NaN  Southampton    no   True       30.0   

   family_no  
0          2  
1          1  
2          1  
3          1  
4          5  
5          3  
6          2  
7          3  
8          1  
9          1

In [144]:
datasets.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  family_no  
0    man        True  NaN  Southampton    no  False       32.0          2  
1  woman       False    C    Cherbourg   yes  False       48.0          2  
2  woman       False  NaN  Southampton   yes   True       36.0          1  
3  woman       False    C  Southampton   yes  False       45.0          2  
4    man        True  NaN  Southampton    no   True       45.0          1

In [153]:
# pclass == 3 인 데이터만 확인하고 싶다면?
# boolean_index

# 선실등급이 3등급인 sex , who 확인하고 싶다면?

boolean_idx = datasets['pclass'] == 3 
datasets[boolean_idx].iloc[ 0:10 , [2 , 9] ]


sex    who
0     male    man
2   female  woman
4     male    man
5     male    man
7     male  child
8   female  woman
10  female  child
12    male    man
13    male    man
14  female  child

In [161]:
print(' 나이가 60이상인 정보만 출력한다면? -')
print(' pclass , survived , who - ')
print(' loc[] 이용해서 작업해 본다면 - ')

# datasets['age'] >= 60 
# datasets[ datasets['age'] >= 60  ][ ['pclass', 'survived' , 'who'] ]

datasets.loc[ datasets['age'] >= 60  , ['pclass', 'survived' , 'who'] ].head()

 나이가 60이상인 정보만 출력한다면? -
 pclass , survived , who - 
 loc[] 이용해서 작업해 본다면 - 


pclass  survived  who
33        2         0  man
54        1         0  man
96        1         0  man
116       3         0  man
170       1         0  man

In [165]:
print(' 여러개의 복합 조건을 이용해서 boolean index를 만들 수 있다. & , | , !')
print(' 나이가 60보다 크고 선실등급이 1등급이고 성별이 여자인 데이터만 출력한다면?  -')
print()
datasets[ (datasets['age'] > 60) & (datasets['pclass'] == 1) & (datasets['sex'] == 'female') ]

 여러개의 복합 조건을 이용해서 boolean index를 만들 수 있다. & , | , !
 나이가 60보다 크고 선실등급이 1등급이고 성별이 여자인 데이터만 출력한다면?  -



survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
275         1       1  female  63.0      1      0  77.9583        S  First   
829         1       1  female  62.0      0      0  80.0000      NaN  First   

       who  adult_male deck  embark_town alive  alone  age_by_10  family_no  
275  woman       False    D  Southampton   yes  False       73.0          2  
829  woman       False    B          NaN   yes   True       72.0          1

In [171]:
print(' 승객의 평균나이를 구한다면?  -')
print()
print( datasets['age'].mean() )
print( datasets.loc[ : , 'age'].mean() )

 승객의 평균나이를 구한다면?  -

29.69911764705882
29.69911764705882


In [172]:
print(' 여성승객의 평균나이를 구한다면?  -')
print()
print( datasets['age'][ datasets['sex'] == 'female'].mean() )
print( datasets.loc[ datasets['sex'] == 'female' , 'age'].mean() )

 여성승객의 평균나이를 구한다면?  -

27.915708812260537
27.915708812260537


In [173]:
print(' 1등급 선실의 여성승객의 평균나이를 구한다면?  -')
print()
print( datasets['age'][(datasets['pclass'] == 1) & (datasets['sex'] == 'female') ].mean() )
print( datasets.loc[ (datasets['pclass'] == 1) & (datasets['sex'] == 'female') , 'age'].mean() )

 1등급 선실의 여성승객의 평균나이를 구한다면?  -

34.61176470588235
34.61176470588235


#### 정렬
- sort_index
- sort_values

In [177]:
sort_frm = pd.DataFrame(np.random.randint(0, 10 , (6,4)))
sort_frm

0  1  2  3
0  0  7  0  5
1  9  4  2  5
2  4  0  0  5
3  0  3  2  6
4  7  3  4  6
5  2  0  6  7

In [183]:
sort_frm.index   = pd.date_range('20210901' , periods=6)
sort_frm.columns = ['A', 'B', 'C', 'D'] 
sort_frm

A  B  C  D
2021-09-01  0  7  0  5
2021-09-02  9  4  2  5
2021-09-03  4  0  0  5
2021-09-04  0  3  2  6
2021-09-05  7  3  4  6
2021-09-06  2  0  6  7

In [191]:
random_date = np.random.permutation(sort_frm.index)
random_date

r_sort_frm = sort_frm.reindex(index   = random_date , 
                              columns = ['B', 'A', 'D' , 'C'])
r_sort_frm

B  A  D  C
2021-09-01  7  0  5  0
2021-09-04  3  0  6  2
2021-09-03  0  4  5  0
2021-09-02  4  9  5  2
2021-09-05  3  7  6  4
2021-09-06  0  2  7  6

In [198]:
print('sort_index(axis =  , ascending = ) - ')
r_sort_frm.sort_index(axis=1, ascending = False)

sort_index(axis =  , ascending = ) - 


D  C  B  A
2021-09-01  5  0  7  0
2021-09-04  6  2  3  0
2021-09-03  5  0  0  4
2021-09-02  5  2  4  9
2021-09-05  6  4  3  7
2021-09-06  7  6  0  2

In [202]:
print('sort_values(by =  , ascending = ) - ')
print('열의 값을 기준으로 행 정렬한다 - ')
r_sort_frm.sort_values(by=['B','A'] , ascending = False)

sort_values(by =  , ascending = ) - 
열의 값을 기준으로 행 정렬한다 - 


B  A  D  C
2021-09-01  7  0  5  0
2021-09-02  4  9  5  2
2021-09-05  3  7  6  4
2021-09-04  3  0  6  2
2021-09-03  0  4  5  0
2021-09-06  0  2  7  6

In [206]:
print(' 타이타닉에서 승객의 나이를 기준으로 내림차순정렬을 한다면? - ')
datasets.sort_values(by='age' , ascending = False).head()

 타이타닉에서 승객의 나이를 기준으로 내림차순정렬을 한다면? - 


survived  pclass   sex   age  sibsp  parch     fare embarked  class  who  \
630         1       1  male  80.0      0      0  30.0000        S  First  man   
851         0       3  male  74.0      0      0   7.7750        S  Third  man   
493         0       1  male  71.0      0      0  49.5042        C  First  man   
96          0       1  male  71.0      0      0  34.6542        C  First  man   
116         0       3  male  70.5      0      0   7.7500        Q  Third  man   

     adult_male deck  embark_town alive  alone  age_by_10  family_no  
630        True    A  Southampton   yes   True       90.0          1  
851        True  NaN  Southampton    no   True       84.0          1  
493        True  NaN    Cherbourg    no   True       81.0          1  
96         True    A    Cherbourg    no   True       81.0          1  
116        True  NaN   Queenstown    no   True       80.5          1

In [220]:
print(' 타이타닉에서 승객에 대해서 - ')

print(' 성별의 인원수 - ' )
print()
print(datasets['sex'].value_counts().sort_values(ascending=False))
print()

print(' 나이별 인원수 - ')
print()
print(datasets['age'].value_counts().sort_values(ascending=False))
print()

print(' 선실별 인원수 - ')
print()
print(datasets['pclass'].value_counts().sort_values(ascending=False))
print()

print(' 사망/생존별 인원수를 구한다면?  - ')
print()
print(datasets['alive'].value_counts().sort_values(ascending=False))
print()


 타이타닉에서 승객에 대해서 - 
 성별의 인원수 - 

male      577
female    314
Name: sex, dtype: int64

 나이별 인원수 - 

24.00    30
22.00    27
18.00    26
28.00    25
19.00    25
         ..
0.67      1
20.50     1
66.00     1
24.50     1
12.00     1
Name: age, Length: 88, dtype: int64

 선실별 인원수 - 

3    491
1    216
2    184
Name: pclass, dtype: int64

 사망/생존별 인원수를 구한다면?  - 

no     549
yes    342
Name: alive, dtype: int64



- rank()

In [231]:
print(' 타이타닉에서 승객의 나이를 기준으로 내림차순정렬을하고 순위를 부여한다면? - ')
# print( type(datasets.sort_values(by='age' , ascending = False) ) )
rank = datasets.sort_values(by='age' , ascending = False)['age'].rank(ascending = False)
rank

 타이타닉에서 승객의 나이를 기준으로 내림차순정렬을하고 순위를 부여한다면? - 


630    1.0
851    2.0
493    3.5
96     3.5
116    5.0
      ... 
859    NaN
863    NaN
868    NaN
878    NaN
888    NaN
Name: age, Length: 891, dtype: float64

In [232]:
datasets.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  family_no  \
0    man        True  NaN  Southampton    no  False       32.0          2   
1  woman       False    C    Cherbourg   yes  False       48.0          2   
2  woman       False  NaN  Southampton   yes   True       36.0          1   
3  woman       False    C  Southampton   yes  False       45.0          2   
4    man        True  NaN  Southampton    no   True       45.0          1   

    rank  
0  497.0  
1  183.0  
2  404.5  
3  226.5  
4  226.5

#### year2020_baby_name.csv

In [239]:
name_dataset = pd.read_csv('./data/year2020_baby_name.csv' , sep="," , encoding='utf-8')
print('type - ')
print( type(name_dataset))
print()
name_dataset.info()

type - 
<class 'pandas.core.frame.DataFrame'>

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33838 entries, 0 to 33837
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   NAME    33838 non-null  object
 1   GENDER  33838 non-null  object
 2   COUNT   33838 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 793.2+ KB


In [240]:
name_dataset.head()

NAME GENDER  COUNT
0  Isabella      F  22731
1    Sophia      F  20477
2      Emma      F  17179
3    Olivia      F  16860
4       Ava      F  15300

In [243]:
sort_name_dataset = name_dataset.sort_values(by='COUNT' , ascending = False)
sort_name_dataset.head()

NAME GENDER  COUNT
0      Isabella      F  22731
19698     Jacob      M  21875
1        Sophia      F  20477
19699     Ethan      M  17866
2          Emma      F  17179

In [246]:
sort_name_dataset.reset_index(inplace = True)


In [248]:
sort_name_dataset.drop(['index'], axis = 1 , inplace = True)
sort_name_dataset

NAME GENDER  COUNT
0      Isabella      F  22731
1         Jacob      M  21875
2        Sophia      F  20477
3         Ethan      M  17866
4          Emma      F  17179
...         ...    ...    ...
33833  Mccauley      F      5
33834     Mazal      F      5
33835    Mayzee      F      5
33836    Maythe      F      5
33837     Zzyzx      M      5

[33838 rows x 3 columns]

In [250]:
rank_series = sort_name_dataset['COUNT'].rank(ascending = False)
rank_series

0            1.0
1            2.0
2            3.0
3            4.0
4            5.0
          ...   
33833    31407.5
33834    31407.5
33835    31407.5
33836    31407.5
33837    31407.5
Name: COUNT, Length: 33838, dtype: float64

In [251]:
rank = rank_series.astype('int64')
sort_name_dataset['rank'] = rank

In [252]:
sort_name_dataset

NAME GENDER  COUNT   rank
0      Isabella      F  22731      1
1         Jacob      M  21875      2
2        Sophia      F  20477      3
3         Ethan      M  17866      4
4          Emma      F  17179      5
...         ...    ...    ...    ...
33833  Mccauley      F      5  31407
33834     Mazal      F      5  31407
33835    Mayzee      F      5  31407
33836    Maythe      F      5  31407
33837     Zzyzx      M      5  31407

[33838 rows x 4 columns]

In [257]:
# sort_name_dataset['GENDER'] == 'M'
m_gender_frm = sort_name_dataset[ sort_name_dataset['GENDER'] == 'M' ]
f_gender_frm = sort_name_dataset[ sort_name_dataset['GENDER'] == 'F' ]

In [258]:
f_gender_frm

NAME GENDER  COUNT   rank
0      Isabella      F  22731      1
2        Sophia      F  20477      3
4          Emma      F  17179      5
8        Olivia      F  16860      9
14          Ava      F  15300     15
...         ...    ...    ...    ...
33832    Mckell      F      5  31407
33833  Mccauley      F      5  31407
33834     Mazal      F      5  31407
33835    Mayzee      F      5  31407
33836    Maythe      F      5  31407

[19698 rows x 4 columns]